description: This is a template researchers can walk away with and create their own Portfolio.
datelastupdated: Nov 2021
twitterurl: https://twitter.com/amandamiottogu
github: https://github.com/amandamiotto
linkedin: https://www.linkedin.com/in/amanda-miotto-94b8ba13/
fullnameofperson: Amanda Miotto
selfIdentification: eResearch Analyst and lover of Science and IT
colour1: "#353535"  # sidebar background 
colour2: "#FFFFFF"  # colour of name and desc
colour3: "#3C6E71"  # colour of Menu links
colour4: "#d4dfc7ff" # trying to be background colour - still experimenting 
colour5: "#284B63" # menu link colour when hover%
