title: Portfolio of Amanda Miotto
description: This is a template researchers can walk away with and create their own Portfolio.
datelastupdated: Nov 2021
twitterurl: https://twitter.com/amandamiottogu
github: https://github.com/amandamiotto
linkedin: https://www.linkedin.com/in/amanda-miotto-94b8ba13/
fullnameofperson: Amanda Miotto
selfIdentification: eResearch Analyst and lover of Science and IT
colour1: "#725752ff"
colour2: "#878e88ff"
colour3: "#96c0b7ff"
colour4: "#d4dfc7ff"
colour5: "#fef6c9ff"
