title: Portfolio of Amanda Miotto
description: This is a template researchers can walk away with and create their own Portfolio.
datelastupdated: Nov 2021
twitterurl: twitter.com/amandamiottogu
github: https://github.com/amandamiotto
linkedin: https://www.linkedin.com/in/amanda-miotto-94b8ba13/
